package com.mycompany.projeto_integrador_db.telas;

import com.mycompany.projeto_integrador_db.persistencias.Checkbox;
import com.mycompany.projeto_integrador_db.persistencias.TarefaU;
import com.mycompany.projeto_integrador_db.persistencias.TarefaU_JPA;
import com.mycompany.projeto_integrador_db.persistencias.Usuario;
import java.awt.Component;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

public class JanelaTarefaProg extends javax.swing.JFrame {

    
    private TarefaU tarefaID; 
    private int idID;
    public JanelaTarefaProg() {
        initComponents();
    }
    
    public JanelaTarefaProg(Usuario usuarioSelect,TarefaU tarefaSelected) {
         initComponents();
         
         tarefaID = tarefaSelected;
         idID = tarefaSelected.getId();
         
    }
    
    private void adicionarCheckbox() {
        String nome = nomecheckbox.getText().trim(); 

        if (!nome.isEmpty()) { 
            JCheckBox checkBox = new JCheckBox(nome); 
            checkboxPanel.add(checkBox); 
            
            checkBox.setEnabled(false);
            
            checkboxPanel.revalidate();
            checkboxPanel.repaint();

           
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, insira um nome para o checkbox.");
        }
       
    }
    
    private boolean verificarCheckboxes() {
        Component[] components = checkboxPanel.getComponents(); 
        boolean todosMarcados = true; 

        for (Component component : components) {
            if (component instanceof JCheckBox) { 
                JCheckBox checkBox = (JCheckBox) component;
                if (!checkBox.isSelected()) {
                    todosMarcados = false; 
                    break; 
                }
            }
        }
        
        if (todosMarcados) {
            JOptionPane.showMessageDialog(this, "Tarefa Concluida!");
        } 
        
        return todosMarcados;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        checkboxPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        nomecheckbox = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        nomeTarefaProg = new javax.swing.JTextField();
        adicionarCheck = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        salvar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        voltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(854, 362));
        setPreferredSize(new java.awt.Dimension(827, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        checkboxPanel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(checkboxPanel);
        checkboxPanel.setBounds(510, 100, 280, 190);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Checkbox da Tarefa");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(570, 10, 160, 30);

        nomecheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomecheckboxActionPerformed(evt);
            }
        });
        jPanel1.add(nomecheckbox);
        nomecheckbox.setBounds(50, 150, 210, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Nome da Tarefa ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 240, 140, 25);

        nomeTarefaProg.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nomeTarefaProg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTarefaProgActionPerformed(evt);
            }
        });
        jPanel1.add(nomeTarefaProg);
        nomeTarefaProg.setBounds(40, 280, 270, 31);

        adicionarCheck.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        adicionarCheck.setText("Adicionar");
        adicionarCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarCheckActionPerformed(evt);
            }
        });
        jPanel1.add(adicionarCheck);
        adicionarCheck.setBounds(270, 150, 100, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Gostaria de adicionar uma checkbox?");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 110, 310, 40);

        jLabel7.setText("Checkbox");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(70, 80, 70, 16);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/layout2 - pequenolimpo.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 70, 420, 150);

        salvar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        salvar.setText("Salvar");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });
        jPanel1.add(salvar);
        salvar.setBounds(510, 310, 100, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tarefa Progressiva");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 20, 170, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/layout11-pequenolimpo.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 0, 480, 390);

        voltar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        jPanel1.add(voltar);
        voltar.setBounds(680, 310, 100, 32);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/layout4 - pequenolimpo.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(490, 20, 370, 370);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 391));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarCheckActionPerformed
        adicionarCheckbox();
        
        String descr = nomecheckbox.getText();
        boolean marcada = verificarCheckboxes();
        
        
        
        Checkbox check = new Checkbox(0,descr,marcada,tarefaID);
        TarefaU_JPA.cadastrarCheckbox(check);
        
        nomecheckbox.setText("");
        
    }//GEN-LAST:event_adicionarCheckActionPerformed

    private void nomeTarefaProgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTarefaProgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTarefaProgActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void nomecheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomecheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomecheckboxActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
       
        String tarefa;
        boolean feita;
        
        tarefa = nomeTarefaProg.getText();
        feita = verificarCheckboxes();
        
        TarefaU_JPA.atualizarTarefa(idID,tarefa,feita);
        
        dispose();
        
    }//GEN-LAST:event_salvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaTarefaProg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaTarefaProg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaTarefaProg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaTarefaProg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaTarefaProg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarCheck;
    private javax.swing.JPanel checkboxPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeTarefaProg;
    private javax.swing.JTextField nomecheckbox;
    private javax.swing.JButton salvar;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
