package com.mycompany.projeto_integrador_db.telas;

import com.mycompany.projeto_integrador_db.persistencias.Usuario;
import com.mycompany.projeto_integrador_db.persistencias.UsuarioJPA;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;


public class Login extends javax.swing.JFrame {
    
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        
        UsuarioJPA.preencherComboBox(usuarioantigo);
    }
    
     public Login(Usuario user) {
        initComponents();
        setLocationRelativeTo(null);
        
        UsuarioJPA.preencherComboBox(usuarioantigo);
        
    }
    
    
    public static boolean usuarioExistente(String novaString, JComboBox<String> comboBox) {
        for (int i = 0; i < comboBox.getItemCount(); i++) {    
            if (comboBox.getItemAt(i).equals(novaString)) {
                return false;  
            }
        }
        return true;  
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        novousuarionome = new javax.swing.JTextField();
        entrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        usuarioantigo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        paineldefundolabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titulo.setText("Informe o seu nome de usuário");
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 350, 40));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, 120, 30));

        novousuarionome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        novousuarionome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novousuarionomeActionPerformed(evt);
            }
        });
        jPanel1.add(novousuarionome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 460, 60));

        entrar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        entrar.setText("Entrar");
        entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarActionPerformed(evt);
            }
        });
        jPanel1.add(entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 600, 160, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("Já é Usuario? ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 220, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Nome do Usuário");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 300, 50));

        usuarioantigo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        usuarioantigo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o Perfil" }));
        usuarioantigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioantigoActionPerformed(evt);
            }
        });
        jPanel1.add(usuarioantigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 460, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setText("Reward List");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 280, 80));

        paineldefundolabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/layout11-2.png"))); // NOI18N
        paineldefundolabel.setMaximumSize(new java.awt.Dimension(946, 765));
        paineldefundolabel.setPreferredSize(new java.awt.Dimension(946, 780));
        jPanel1.add(paineldefundolabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void novousuarionomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novousuarionomeActionPerformed

    }//GEN-LAST:event_novousuarionomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarActionPerformed
      
        if (!novousuarionome.getText().equalsIgnoreCase("") && usuarioExistente(novousuarionome.getText(),usuarioantigo) == true){
        String usernovo;
        usernovo = novousuarionome.getText();
        
        Usuario newuser = new Usuario(0,usernovo); 
      
        UsuarioJPA.cadastrarUsuario(newuser);
        
        usuarioantigo.addItem(novousuarionome.getText());
        
        TelarRegistroTarefa telaregistro = new TelarRegistroTarefa(newuser);
        telaregistro.setVisible(true);
        
        novousuarionome.setText("");
        
        System.out.println(newuser);
        
        JOptionPane.showMessageDialog(null,"Bem Vindo a lista de tarefas " + usernovo + "! \n"
                + "Clique em - Única - para criar tarefas que tenham apenas um objetivo!\n"
                + "Clique em - Progressiva - para criar tarefas que sejam melhores executadas em passos menores!\n"
                + "Quando terminar sua tarefa ou algum passo especifico, selecione a tarefa na lista e clique no botão - Concluir- !\n"
                + "Lembre-se que nós disponibilizamos uma lojinha tambem! Vai lá conferir :) !");
        
        }else if (usuarioExistente(novousuarionome.getText(),usuarioantigo) == false){
            JOptionPane.showMessageDialog(null, "Usuário já existe!");
        }else{
                    
            String userlogadoNome = (String) usuarioantigo.getSelectedItem();
            
            Usuario userlogado = UsuarioJPA.buscarUsuarioPorNome(userlogadoNome);
            
            TelarRegistroTarefa telaregistro = new TelarRegistroTarefa(userlogado);
            telaregistro.setVisible(true);
    }

    }//GEN-LAST:event_entrarActionPerformed

    private void usuarioantigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioantigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioantigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton entrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField novousuarionome;
    private javax.swing.JLabel paineldefundolabel;
    private javax.swing.JLabel titulo;
    private javax.swing.JComboBox<String> usuarioantigo;
    // End of variables declaration//GEN-END:variables
}
