package com.mycompany.projeto_integrador_db.telas;

import com.mycompany.projeto_integrador_db.persistencias.TarefaU;
import com.mycompany.projeto_integrador_db.persistencias.TarefaU_JPA;
import com.mycompany.projeto_integrador_db.persistencias.Usuario;
import com.mycompany.projeto_integrador_db.persistencias.UsuarioJPA;
import java.awt.Font;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


public class TelarRegistroTarefa extends javax.swing.JFrame {
    
    private Usuario idUsuario;
    private int moedas = 0;
    
    public TelarRegistroTarefa() {
        initComponents();  
        listanovas.setFont(new Font("Arial", Font.PLAIN, 16));
        listanovas.setRowHeight(30);
        
        listaconcluidas.setFont(new Font("Arial", Font.PLAIN, 16));
        listaconcluidas.setRowHeight(30);
    }  
    
    public TelarRegistroTarefa(Usuario usuarioSelect) {
        initComponents(); 
        setImagem("src/main/resources/imagens/layout11-2.png");
        
       idUsuario = usuarioSelect;
       logado.setText(idUsuario.getLogin());
       
       listanovas.setFont(new Font("Arial", Font.PLAIN, 16));
       listanovas.setRowHeight(30);
       
       listaconcluidas.setFont(new Font("Arial", Font.PLAIN, 16));
       listaconcluidas.setRowHeight(30);
       
    }
    
    
    private int getIdItemSelecionado(JTable tabela) {
    int posicao = tabela.getSelectedRow(); 
    if (posicao == -1) {

        return -1; 
    }
    
    return (int) tabela.getValueAt(posicao, 0);
}
    
    
    private DefaultTableModel montarTabela(List<TarefaU> tarefas) {
    String[] colunas = { "ID", "Nome da Tarefa", "Concluída" };  
    Object[][] dados = new Object[tarefas.size()][colunas.length];

    for (int i = 0; i < tarefas.size(); i++) {
        TarefaU tarefa = tarefas.get(i);
        dados[i][0] = tarefa.getId();
        dados[i][1] = tarefa.getDescricao();
        dados[i][2] = tarefa.isConcluida() ? "Sim" : "Não"; 
    }
        
    return new DefaultTableModel(dados, colunas);
}
    
    public final void setImagem(String imagePath) {
        ImageIcon icon = new ImageIcon(imagePath);
        jLabel2.setIcon(icon); 
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paineldefundo = new javax.swing.JPanel();
        conclusaobotao = new javax.swing.JButton();
        lojabotao = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listanovas = new javax.swing.JTable();
        barraprogresso = new javax.swing.JProgressBar();
        excluirtarefaC = new javax.swing.JButton();
        excluirtarefa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaconcluidas = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        logado = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        tarefaprogressiva = new javax.swing.JButton();
        tarefaunica = new javax.swing.JButton();
        numeromoedas = new javax.swing.JLabel();
        coinimage = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        adcimage = new javax.swing.JLabel();
        tarefaconcimage = new javax.swing.JLabel();
        novatarefaimage = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        paineldefundo.setMinimumSize(new java.awt.Dimension(946, 773));
        paineldefundo.setPreferredSize(new java.awt.Dimension(946, 768));
        paineldefundo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                paineldefundoFocusGained(evt);
            }
        });
        paineldefundo.setLayout(null);

        conclusaobotao.setBackground(new java.awt.Color(153, 153, 255));
        conclusaobotao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        conclusaobotao.setForeground(new java.awt.Color(255, 255, 255));
        conclusaobotao.setText("Concluir");
        conclusaobotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conclusaobotaoActionPerformed(evt);
            }
        });
        paineldefundo.add(conclusaobotao);
        conclusaobotao.setBounds(770, 660, 110, 32);

        lojabotao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lojabotao.setText("Loja");
        lojabotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lojabotaoActionPerformed(evt);
            }
        });
        paineldefundo.add(lojabotao);
        lojabotao.setBounds(750, 50, 130, 40);

        jScrollPane3.setViewportView(listanovas);

        paineldefundo.add(jScrollPane3);
        jScrollPane3.setBounds(50, 350, 340, 340);

        barraprogresso.setForeground(new java.awt.Color(153, 153, 255));
        paineldefundo.add(barraprogresso);
        barraprogresso.setBounds(110, 200, 260, 30);

        excluirtarefaC.setBackground(new java.awt.Color(255, 51, 51));
        excluirtarefaC.setForeground(new java.awt.Color(255, 255, 255));
        excluirtarefaC.setText("Excluir");
        excluirtarefaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirtarefaCActionPerformed(evt);
            }
        });
        paineldefundo.add(excluirtarefaC);
        excluirtarefaC.setBounds(610, 200, 100, 23);

        excluirtarefa.setBackground(new java.awt.Color(255, 51, 51));
        excluirtarefa.setForeground(new java.awt.Color(255, 255, 255));
        excluirtarefa.setText("Excluir");
        excluirtarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirtarefaActionPerformed(evt);
            }
        });
        paineldefundo.add(excluirtarefa);
        excluirtarefa.setBounds(180, 310, 100, 23);

        listaconcluidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(listaconcluidas);

        paineldefundo.add(jScrollPane1);
        jScrollPane1.setBounds(490, 240, 330, 310);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Progresso Diário");
        paineldefundo.add(jLabel4);
        jLabel4.setBounds(150, 150, 180, 40);

        logado.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        logado.setForeground(new java.awt.Color(255, 255, 255));
        paineldefundo.add(logado);
        logado.setBounds(110, 0, 460, 40);

        usuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        usuario.setForeground(new java.awt.Color(255, 255, 255));
        usuario.setText("Usuário:");
        paineldefundo.add(usuario);
        usuario.setBounds(10, 0, 90, 40);

        tarefaprogressiva.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tarefaprogressiva.setText("Progressiva");
        tarefaprogressiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarefaprogressivaActionPerformed(evt);
            }
        });
        paineldefundo.add(tarefaprogressiva);
        tarefaprogressiva.setBounds(450, 620, 130, 40);

        tarefaunica.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tarefaunica.setText("Única");
        tarefaunica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarefaunicaActionPerformed(evt);
            }
        });
        paineldefundo.add(tarefaunica);
        tarefaunica.setBounds(630, 620, 110, 40);

        numeromoedas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        numeromoedas.setText("0");
        paineldefundo.add(numeromoedas);
        numeromoedas.setBounds(40, 170, 30, 30);

        coinimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/coin.png"))); // NOI18N
        paineldefundo.add(coinimage);
        coinimage.setBounds(20, 120, 50, 50);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tarefas Concluidas");
        paineldefundo.add(jLabel6);
        jLabel6.setBounds(580, 160, 170, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Novas Tarefas");
        paineldefundo.add(jLabel5);
        jLabel5.setBounds(170, 270, 130, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Adicionar nova tarefa");
        paineldefundo.add(jLabel3);
        jLabel3.setBounds(440, 570, 190, 20);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Gerenciador de Lista de Tarefas");
        paineldefundo.add(jLabel1);
        jLabel1.setBounds(90, 50, 380, 30);

        adcimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/layout2 - pequeno.png"))); // NOI18N
        paineldefundo.add(adcimage);
        adcimage.setBounds(400, 550, 420, 170);

        tarefaconcimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/layout4 - clarolimpa.png"))); // NOI18N
        paineldefundo.add(tarefaconcimage);
        tarefaconcimage.setBounds(450, 150, 420, 480);

        novatarefaimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/layout4 - clarolimpa.png"))); // NOI18N
        paineldefundo.add(novatarefaimage);
        novatarefaimage.setBounds(20, 260, 430, 480);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/layout11-2.png"))); // NOI18N
        paineldefundo.add(jLabel2);
        jLabel2.setBounds(0, 0, 946, 773);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paineldefundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paineldefundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tarefaunicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarefaunicaActionPerformed
       JanelaTarefaUnica telaunica = new JanelaTarefaUnica(idUsuario);
        telaunica.setVisible(true);
      
    }//GEN-LAST:event_tarefaunicaActionPerformed

    private void tarefaprogressivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarefaprogressivaActionPerformed
       
        TarefaU novaTarefaProg = new TarefaU(0,idUsuario,"",false);
        TarefaU_JPA.cadastrar(novaTarefaProg);
        
        
        JanelaTarefaProg telaprog = new JanelaTarefaProg(idUsuario,novaTarefaProg);
        telaprog.setVisible(true);
    }//GEN-LAST:event_tarefaprogressivaActionPerformed

    private void lojabotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lojabotaoActionPerformed
        JanelaLoja loja = new JanelaLoja(this,Integer.parseInt(numeromoedas.getText()));
        loja.setVisible(true);
    }//GEN-LAST:event_lojabotaoActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
     
    }//GEN-LAST:event_formFocusGained

    private void paineldefundoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paineldefundoFocusGained
        
    }//GEN-LAST:event_paineldefundoFocusGained

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
      
        int idUsu = UsuarioJPA.buscarId(idUsuario);
        
        listanovas.setModel(montarTabela(TarefaU_JPA.listar3(idUsu)));
        jScrollPane3.setViewportView(listanovas);
        
        System.out.println(idUsu);
        
        listaconcluidas.setModel(montarTabela(TarefaU_JPA.conclusao(idUsu)));
        jScrollPane1.setViewportView(listaconcluidas);
        
        int maximo;
        int prog;
        
        maximo = TarefaU_JPA.MaximoProgresso(idUsu);
        prog = TarefaU_JPA.Progresso(idUsu);
        
        barraprogresso.setMinimum(0);
        barraprogresso.setMaximum(maximo);
        
        barraprogresso.setValue(prog);
        
        barraprogresso.setStringPainted(true);
        
        
        
    }//GEN-LAST:event_formWindowGainedFocus

    private void excluirtarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirtarefaActionPerformed
    
    int idNovas = getIdItemSelecionado(listanovas);
    if (idNovas != -1) {
        TarefaU_JPA.excluir(idNovas);
        
        JOptionPane.showMessageDialog(null, "Tarefa excluida com sucesso!");
        return; 
    }
    
    JOptionPane.showMessageDialog(null, "Selecione um item em uma das tabelas.");
        
    }//GEN-LAST:event_excluirtarefaActionPerformed

    private void excluirtarefaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirtarefaCActionPerformed
        int idConcluidas = getIdItemSelecionado(listaconcluidas);
        
        if (idConcluidas != -1) {
            TarefaU_JPA.excluir(idConcluidas); 
        
            JOptionPane.showMessageDialog(null, "Tarefa excluida com sucesso!");
            return; 
        }
    JOptionPane.showMessageDialog(null, "Selecione um item em uma das tabelas.");
    
    }//GEN-LAST:event_excluirtarefaCActionPerformed

    private void conclusaobotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conclusaobotaoActionPerformed
        
        int selectedRow = listanovas.getSelectedRow();

if (selectedRow != -1) {
    int id = (int) listanovas.getValueAt(selectedRow, 0);
    int selecao = TarefaU_JPA.buscarQuantidadeCheckbox(id);

    if (selecao != 0) {
        TarefaU_JPA.buscarTarefa(id);
        JanelaAtualizacaoProg telaprog = new JanelaAtualizacaoProg(id);
        telaprog.setVisible(true);
        
         if (TarefaU_JPA.moedas(id)) {
            moedas += 1;
            numeromoedas.setText(String.valueOf(moedas));
        
        
    }}else {
        int resposta = JOptionPane.showConfirmDialog(null, "Você tem certeza que deseja concluir a tarefa?", "Confirmação", JOptionPane.YES_NO_OPTION);
        
        if (resposta == JOptionPane.YES_OPTION) {
            TarefaU_JPA.marcarComoConcluida(id); 

            if (TarefaU_JPA.moedas(id)) {
                moedas += 1;
                numeromoedas.setText(String.valueOf(moedas));
            }
        } else {
            JOptionPane.showMessageDialog(this, "Nenhuma tarefa nova selecionada.");
        }
    }
} else {
    JOptionPane.showMessageDialog(this, "Por favor, selecione uma tarefa antes de continuar.");
}
       
    }//GEN-LAST:event_conclusaobotaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelarRegistroTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelarRegistroTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelarRegistroTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelarRegistroTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelarRegistroTarefa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adcimage;
    private javax.swing.JProgressBar barraprogresso;
    private javax.swing.JLabel coinimage;
    private javax.swing.JButton conclusaobotao;
    private javax.swing.JButton excluirtarefa;
    private javax.swing.JButton excluirtarefaC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable listaconcluidas;
    private javax.swing.JTable listanovas;
    private javax.swing.JLabel logado;
    private javax.swing.JButton lojabotao;
    private javax.swing.JLabel novatarefaimage;
    private javax.swing.JLabel numeromoedas;
    private javax.swing.JPanel paineldefundo;
    private javax.swing.JLabel tarefaconcimage;
    private javax.swing.JButton tarefaprogressiva;
    private javax.swing.JButton tarefaunica;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
